### ISSUE TITLE
想要用indexPath.row去取得我plist的資料時出錯

### ISSUE THREAD

**Issue by josh790521** [roberthsu2003/2019Iphone1#2]
<img width="1276" alt="截圖 2021-05-11 下午3 04 23" src="https://user-images.githubusercontent.com/78533594/117772839-30cdc000-b26a-11eb-84c0-8737b5686121.png">
老師你好，我是睿誠，一直找不到哪邊出錯，是照老師的範例一步一步做還是出錯

**Comment by roberthsu2003** [comment]
> <img alt="截圖 2021-05-11 下午3 04 23" width="1276" src="https://user-images.githubusercontent.com/78533594/117772839-30cdc000-b26a-11eb-84c0-8737b5686121.png">
> 
> 老師你好，我是睿誠，一直找不到哪邊出錯，是照老師的範例一步一步做還是出錯

<img width="1237" alt="截圖 2021-05-11 下午6 44 07" src="https://user-images.githubusercontent.com/1614274/117803208-ef98d880-b288-11eb-8506-b37850731db4.png">
